### ISSUE TITLE
port to kf5

### ISSUE THREAD

**Issue by brothermechanic** [kayosiii/kde-thumbnailer-blender#1]
Hello
Thank toy for useful addon for dolphin!
Do you plan port it to kf5?

**Comment by kayosiii** [comment]
I have :)

I just need time to commit it up to the KDE Devs

**Comment by brothermechanic** [comment]
Thank you!

**Comment by JenaPlinsky** [comment]
@kayosiii 
Ciao  Great plugIn  !!! How can I install it on openSUSE Plasma ?

**Comment by brothermechanic** [comment]
JenaPlinsky, use gentoo!
http://gpo.zugaina.org/kde-apps/kde5-thumbnailer-blender
